=== GanapriyaS/Web-Fundamentals/xml/student.dtd
<!ELEMENT college (student+)>
<!ATTLIST college
  code CDATA #REQUIRED
  name CDATA #REQUIRED>
<!ELEMENT student (rollno,name,branch,year,email)>
<!ELEMENT rollno (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT branch (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== GanapriyaS/Web-Fundamentals/xml/student.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<?xml-stylesheet type="text/xsl" href="student.xsl"?>
<!DOCTYPE college SYSTEM "student.dtd">
<college code="2005" name="GCT">
  <student>
    <rollno>101</rollno>
    <name>Arun</name>
    <branch>ME</branch>
    <year>2005</year>
    <email>arun@gmail.com</email>
  </student>
  <student>
    <rollno>132</rollno>
    <name>Sasi</name>
    <branch>ECE</branch>
    <year>2010</year>
    <email>sasi@gmail.com</email>
  </student>
  <student>
    <rollno>183</rollno>
    <name>Priya</name>
    <branch>CSE</branch>
    <year>2011</year>
    <email>priya@gmail.com</email>
  </student>
</college>
